Add evertz ev670
nrkno/netbox-devicetype-library pull request #100
Opened 2024-08-15 12:21 UTC by MicGas

2024-08-16 06:41 UTC, umglurf requested changes

2024-08-16 06:41 UTC, umglurf commented on device-types/Evertz/ev1-FR.yaml
> +comments: ev1-FR er et 1U rack for multiframes processing, deriblant signal processing og multiviewing
some mix of norwegian and english

2024-08-16 06:41 UTC, umglurf commented on device-types/Evertz/ev3-FR.yaml
> +comments: ev3-FR er et 3U rack for multiframes processing, deriblant signal processing og multiviewing
some mix of norwegian and english

2024-08-16 06:41 UTC, umglurf commented on device-types/Evertz/ev6-FR.yaml
> +comments: ev6-FR er et 6U rack for multiframes processing, deriblant signal processing og multiviewing
some mix of norwegian and english

2024-08-16 09:50 UTC, umglurf approved these changes

2024-08-22 08:18 UTC, sjurtf approved these changes

2024-08-22 08:18 UTC, merged