Adding new Riedel devices
nrkno/netbox-devicetype-library pull request #123
Opened 2024-10-09 13:52 UTC by moldennrk

2024-10-29 10:04 UTC, sjurtf requested changes

2024-10-29 10:04 UTC, sjurtf commented on elevation-images/Riedel/riedel-esp-1216hl-front.png
elevantion-images are used to show the device inside a rack view.
The image should only contain the device and not empty space around it.

Could you please modify the images and remove the empty space around the device? Unfortently you might have to crop away the microphone in some of these images as well.

For the images to be included in the import, you must add the following to the corresponding device type yaml file.

```yml
front_image: true
rear_image: true
```

2024-11-01 11:59 UTC, moldennrk commented on device-types/Riedel/artist-1024.yaml
> -front_image: true
These files were based on yaml export from netbox. The image properties are not included in this export.

2024-11-01 14:27 UTC, moldennrk commented on device-types/Riedel/artist-32.yaml
> -rear_image: true
These files were based on yaml export from netbox. The image properties are not included in this export. Fixed in new commit.

2024-11-01 14:27 UTC, moldennrk commented on device-types/Riedel/artist-128.yaml
> -rear_image: true
These files were based on yaml export from netbox. The image properties are not included in this export. Fixed in new commit.

2024-11-01 14:27 UTC, moldennrk commented on device-types/Riedel/artist-64.yaml
> -rear_image: true
These files were based on yaml export from netbox. The image properties are not included in this export. Fixed in new commit.

2024-11-01 14:28 UTC, moldennrk commented on device-types/Riedel/bl-ant-1010-19g-eu-g2.yaml
> +description: Riedel Bolero antenne
Description translated.

2024-11-01 14:28 UTC, moldennrk commented on device-types/Riedel/rsp-1216hl.yaml
> +description: Kommunikasjonspanel 16 knapper
Description translated.

2024-11-01 14:28 UTC, moldennrk commented on device-types/Riedel/rsp-1232hl.yaml
> +description: Kommunikasjon panel med 32 knapper og sterio
Description translated.

2024-11-01 14:28 UTC, moldennrk commented on device-types/Riedel/bl-bpk-1006-19-eu.yaml
> +description: Riedel Bolero 6-knapper handsett
Description translated.

2024-11-01 14:29 UTC, moldennrk commented on elevation-images/Riedel/riedel-esp-1216hl-front.png
Fixed.

2024-11-05 09:53 UTC, sjurtf approved these changes

2024-11-05 09:53 UTC, merged